name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Greet Users
      uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "👋 Hello there! Thanks for opening an issue! How can we assist you today? 😊"
        pr-message: "👋 Hi contributor! Thanks for the pull request! We appreciate your contribution! 🚀"
